import ExcelJS from 'exceljs'
import { formatDate } from '../labels.js'

// The rules every Excel export follows. Plain JavaScript (no app-only
// imports), so the attack test (scripts/rls-attack-test.mjs) builds exactly
// the same files in Node.
//
// RULE: no arithmetic on money here. Every figure, and every total, comes
// from the database. Totals rows are Excel SUM formulas that also carry the
// database's total, so a file is right even before Excel recalculates.

export const MONEY = '"R" #,##0.00'
export const HOURS = '0.00'
export const DATE = 'dd mmm yyyy'
export const DATE_TIME = 'dd mmm yyyy hh:mm'
// The database sends percentages as e.g. 42.9 - shown as "42.9%".
export const PERCENT = '0.0"%"'
export const WHOLE = '0'

export const CONFIDENTIAL = 'Confidential – contains personal information (POPIA)'
export const VAT_NOTE = 'Receipt amounts are the total paid, VAT inclusive.'
export const PROVISIONAL_NOTE = 'Labour and owned plant are provisional: hours × the flat rate on each day, overtime not applied.'

const FORMATS = { money: MONEY, hours: HOURS, date: DATE, percent: PERCENT, whole: WHOLE }

// "2026-03-02" -> a real Excel date for that day (no time-zone shift).
export function excelDate(isoDate) {
  if (!isoDate) return null
  const [year, month, day] = isoDate.slice(0, 10).split('-').map(Number)
  return new Date(Date.UTC(year, month - 1, day))
}

// The time on this device, as Excel should show it.
function excelNow(now) {
  return new Date(
    Date.UTC(now.getFullYear(), now.getMonth(), now.getDate(), now.getHours(), now.getMinutes(), now.getSeconds()),
  )
}

// A number from the database (it may arrive as text) -> a real number.
export const num = (value) => (value === null || value === undefined ? null : Number(value))

// nkutwala_{report}_{project}_{from}_{to}.xlsx
export function exportFilename(report, projectName, from, to) {
  const slug = (projectName ?? 'all projects')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return `nkutwala_${report}_${slug || 'project'}_${from}_${to}.xlsx`
}

export function createWorkbook() {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Nkutwala Site Costing'
  workbook.created = new Date()
  // Excel works out the SUM rows again whenever the file is opened.
  workbook.calcProperties.fullCalcOnLoad = true
  return workbook
}

// One sheet: the title rows, then a table with a bold frozen header,
// filters, sensible widths and (optionally) a SUM totals row.
//   meta:    { report, company, projectName, from, to, generatedBy, generatedAt }
//   notes:   extra lines under the title (shown bold), e.g. CONFIDENTIAL
//   columns: [{ header, key, type: 'text'|'money'|'hours'|'date'|'percent'|'whole', width, dateHeader }]
//            dateHeader: the header is a date ("YYYY-MM-DD"), shown as a real date
//   rows:    [{ [key]: value }] - values exactly as the database sent them
//   totals:  { [key]: the database's total } - a SUM formula carrying it;
//            or { [key]: null } for a SUM formula Excel works out on opening
// Returns { sheet, firstDataRow } (firstDataRow: the first row under the header).
export function addTableSheet(workbook, { name, meta, notes = [], columns, rows, totals }) {
  const sheet = workbook.addWorksheet(name)

  // --- Title rows -------------------------------------------------------------
  sheet.addRow([meta.report]).font = { bold: true, size: 14 }
  sheet.addRow(['Company', meta.company])
  sheet.addRow(['Project', meta.projectName ?? 'All projects'])
  sheet.addRow(['Period', `${formatDate(meta.from)} – ${formatDate(meta.to)}`])
  const generated = sheet.addRow(['Generated', excelNow(meta.generatedAt)])
  generated.getCell(2).numFmt = DATE_TIME
  generated.getCell(2).alignment = { horizontal: 'left' }
  sheet.addRow(['Generated by', meta.generatedBy])
  for (const line of notes) {
    sheet.addRow([line]).font = { bold: true, color: { argb: 'FFC20116' } }
  }
  sheet.addRow([])

  // --- Header -----------------------------------------------------------------
  const header = sheet.addRow(columns.map((column) => (column.dateHeader ? excelDate(column.header) : column.header)))
  const headerRow = header.number
  header.font = { bold: true }
  columns.forEach((column, index) => {
    if (column.dateHeader) header.getCell(index + 1).numFmt = 'dd mmm'
  })
  header.eachCell((cell) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE9E9EB' } }
    cell.border = { bottom: { style: 'thin' } }
    cell.alignment = { vertical: 'middle', wrapText: true }
  })
  sheet.views = [{ state: 'frozen', ySplit: headerRow }]
  sheet.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow, column: columns.length } }

  // --- Data -------------------------------------------------------------------
  const firstDataRow = headerRow + 1
  for (const row of rows) {
    const added = sheet.addRow(
      columns.map(({ key, type }) => {
        const value = row[key]
        if (value === null || value === undefined || value === '') return null
        if (type === 'date') return excelDate(value)
        if (type && type !== 'text') return num(value)
        return value
      }),
    )
    columns.forEach(({ type }, index) => {
      if (FORMATS[type]) added.getCell(index + 1).numFmt = FORMATS[type]
    })
  }
  if (rows.length === 0) sheet.addRow(['Nothing in this period']).font = { italic: true }
  const lastDataRow = sheet.lastRow.number

  // --- Totals row (SUM formulas carrying the database's totals) ---------------
  if (totals) {
    const total = sheet.addRow([])
    total.getCell(1).value = 'Total'
    total.font = { bold: true }
    columns.forEach(({ key, type }, index) => {
      if (!(key in totals)) return
      const cell = total.getCell(index + 1)
      const letter = sheet.getColumn(index + 1).letter
      const formula = `SUM(${letter}${firstDataRow}:${letter}${lastDataRow})`
      const result = num(totals[key])
      cell.value = rows.length === 0 ? (result ?? 0) : result === null ? { formula } : { formula, result }
      if (FORMATS[type]) cell.numFmt = FORMATS[type]
      cell.border = { top: { style: 'thin' } }
    })
  }

  // --- Widths -----------------------------------------------------------------
  columns.forEach((column, index) => {
    sheet.getColumn(index + 1).width = column.width ?? Math.max(12, Math.min(40, String(column.header).length + 2))
  })
  sheet.getColumn(1).width = Math.max(sheet.getColumn(1).width, 16)

  return { sheet, firstDataRow }
}

// The company name and who is exporting, for the title rows.
export async function fetchExportMeta(client, userId) {
  const [company, profile] = await Promise.all([
    client.from('companies').select('name').limit(1).maybeSingle(),
    client.from('profiles').select('full_name').eq('id', userId).maybeSingle(),
  ])
  if (company.error) throw company.error
  if (profile.error) throw profile.error
  return { company: company.data?.name ?? '', generatedBy: profile.data?.full_name ?? '' }
}

export async function call(client, fn, args) {
  const { data, error } = await client.rpc(fn, args)
  if (error) throw error
  return data
}
