// The app's one icon set: Phosphor line icons, imported one at a time so
// only these are bundled. Regular weight in rows; bold where legibility in
// sunlight matters (steppers, back).
export { ArrowCounterClockwiseIcon } from '@phosphor-icons/react/dist/csr/ArrowCounterClockwise'
export { BulldozerIcon } from '@phosphor-icons/react/dist/csr/Bulldozer'
export { CalendarBlankIcon } from '@phosphor-icons/react/dist/csr/CalendarBlank'
export { CaretLeftIcon } from '@phosphor-icons/react/dist/csr/CaretLeft'
export { CaretRightIcon } from '@phosphor-icons/react/dist/csr/CaretRight'
export { CheckCircleIcon } from '@phosphor-icons/react/dist/csr/CheckCircle'
export { CheckIcon } from '@phosphor-icons/react/dist/csr/Check'
export { CoinsIcon } from '@phosphor-icons/react/dist/csr/Coins'
export { ClipboardTextIcon } from '@phosphor-icons/react/dist/csr/ClipboardText'
export { ClockIcon } from '@phosphor-icons/react/dist/csr/Clock'
export { CloudRainIcon } from '@phosphor-icons/react/dist/csr/CloudRain'
export { GasPumpIcon } from '@phosphor-icons/react/dist/csr/GasPump'
export { GearSixIcon } from '@phosphor-icons/react/dist/csr/GearSix'
export { HardHatIcon } from '@phosphor-icons/react/dist/csr/HardHat'
export { HashIcon } from '@phosphor-icons/react/dist/csr/Hash'
export { HourglassIcon } from '@phosphor-icons/react/dist/csr/Hourglass'
export { InfoIcon } from '@phosphor-icons/react/dist/csr/Info'
export { ListChecksIcon } from '@phosphor-icons/react/dist/csr/ListChecks'
export { LockIcon } from '@phosphor-icons/react/dist/csr/Lock'
export { MapPinIcon } from '@phosphor-icons/react/dist/csr/MapPin'
export { MinusCircleIcon } from '@phosphor-icons/react/dist/csr/MinusCircle'
export { MinusIcon } from '@phosphor-icons/react/dist/csr/Minus'
export { PlusCircleIcon } from '@phosphor-icons/react/dist/csr/PlusCircle'
export { PlusIcon } from '@phosphor-icons/react/dist/csr/Plus'
export { SignOutIcon } from '@phosphor-icons/react/dist/csr/SignOut'
export { TagIcon } from '@phosphor-icons/react/dist/csr/Tag'
export { UserCircleIcon } from '@phosphor-icons/react/dist/csr/UserCircle'
export { UsersThreeIcon } from '@phosphor-icons/react/dist/csr/UsersThree'
export { WarningCircleIcon } from '@phosphor-icons/react/dist/csr/WarningCircle'
export { WarningIcon } from '@phosphor-icons/react/dist/csr/Warning'
export { XCircleIcon } from '@phosphor-icons/react/dist/csr/XCircle'
